maps:
  test:
    name: 'Test Map'
    location:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0

scoreboard:
  title: '&4&lMurder Mystery'
  roles:
    murderer: '&4Murderer'
    detective: '&9Detective'
    bystander: '&6Bystander'

time:
  total: 300
  grace: 15