maps:
  map1: # This is an example, use it as a template
    shuffle-exempt: true
    name: 'Map 1'
    spawn:
      location: 0,100,0
      yaw: 0
      pitch: 0
      world: world
    start:
      commands:
      - 'say Game Starting'
      blocks:
        diamond:
          location: 0,99,0
          block: DIAMOND_BLOCK
        chest:
          location: 1,100,0
          block: CHEST
          contents:
            0:
              material: COAL_BLOCK
              amount: 1
              name: '&5Free Coal'
              glow: false
              lore:
              - '&6Its free!'
              - '&3For all!'
            13:
              material: EMERALD
              amount: 5
              name: '&aMystic Emerald'
              glow: true
              lore:
              - '&6Rare and very...'
              - '&cValuable!'
              
    end:
      commands:
      - 'say Game Over!'
      blocks:
        diamond:
          location: 0,99,0
          block: GRASS_BLOCK
        chest:
          location: 1,100,0
          block: AIR
      
enable-deputy: false
innocent-kills-before-detective-kill: 2

items:
  sword:
    name: '&4Murderer Sword'
    type: IRON_SWORD
    lore:
    - 'Used to kill bystanders'
  bow:
    name: '&1Detective Bow'
    type: BOW
    lore:
    - 'Used to kill the murderer'
  deputy-bow:
    name: '&9Deputy Bow'
    type: BOW
    lore:
    - 'Used to kill the murderer'
  potion:
    enabled: false
    name: '&6Invis Potion'
    type: POTION  # POTION / SPLASH_POTION / LINGERING_POTION
    lore:
    - 'Used to hide from the murderer'
    duration: 30
    color: '189,40,42'
    
titles:
  in: 10
  stay: 30
  out: 10
  murderer:
    title: 'You are the &4Murderer'
    subtitle: '&eGoal: Kill all players'
    role: '&4Murderer'
  detective:
    title: 'You are the &1Detective'
    subtitle: '&eGoal: Kill the murderer'
    role: '&1Detective'
  deputy:
    title: 'You are the &9Deputy'
    subtitle: '&eGoal: Help the detective'
    role: '&9Deputy'
  bystander:
    title: 'You are a &6Bystander'
    subtitle: '&eGoal: Don''t get killed'
    role: '&6Bystander'
  dead:
    role: '&4Dead'
  game-over:
    title: 'Game Over'
    subtitle: 'Winner: %winner%'
    roles:
      players: '&6Players'
      murderer: '&4The Murderer'
    
timer:
  team: 'MurderPluginTeam'
  objective: 'MurderPluginObj'
  time: 300
  murder-compass: 150
  grace-period: 20
  restart-delay: 5
  scoreboard:
    title: '&4&lMurder Mystery'
    lines:
    - ''
    - '&aMap: %map%'
    - ''
    - 'Time Remaining: &e%time%'
    - 'Players Remaining: &a%players%'
    - ''
    - 'Role: %role%'
    - ''

debug: false
update-checker: true

lang:
  prefix: '&8[&4MurderMystery&8]&r '
  messages:
    you-died: '&cYou were killed!'
    you-revived: '&aYou were revived'
    player-died: '&cA player died!'
    player-revived: '&aA player was revived'
    player-quit: '&c%player% left the server, so they were removed from the game'
    died-sound: ENTITY_PLAYER_DEATH
    killed-inno: '&6You killed an innocent player!'
    you-got-bow: '&aYou picked up the bow'
    player-got-bow: '&aA player picked up the bow!'
    detective-dead: '&9The detective has been killed! Find the bow to become the next detective!'
    murderer-dead: '&9The murderer has been killed!'
    all-dead: '&9The murderer has killed everyone!'
    time-up: '&9The murderer ran out of time!'
    grace-ending: '&6The grace period ends in %time% seconds'
    grace-ended: '&6The grace period has ended!'
    auto-restart: '&6Starting a new game in %time% seconds!'
    gamemode: '&cYou can''t change your gamemode during a game!'
    drop: '&cYou can''t drop items during a game!'
    gold: '&6You picked up %amount% gold!'
    update: '&aAn update is available! Current version: %current%, new version: %new%. Download it from %url%'
  command:
    usage: '&cUsage: /mm <maps|create|delete|start|shuffle|loop|stop|reload|kill|revive|role|changerole|tt|time>'
    no-perm: '&cYou do not have permission to do that'
    nan: '&cThat is not a valid number'
    invalid: '&cInvalid Usage. Use /mm for help'
    unknown-error: '&cAn error occurred - Check the console for more details'
    not-playing: '&cThat player is not currently in a game'
    not-running: '&cNo game is currently running'
    maps: '&aAvailable Maps:'
    create:
      usage: '&cUsage: /mm create <map> [name]'
      success: '&aSuccessfully created %map% at your location'
      already-exists: '&c%map% already exists'
      not-player: '&cYou must be a player to do that!'
    delete:
      usage: '&cUsage: /mm delete <map>'
      success: '&aSuccessfully deleted %map%'
      doesnt-exist: '&c%map% does not exist'
    reload:
      usage: '&cUsage: /mm reload'
      success: '&aThe config has been reloaded'
    start:
      usage: '&cUsage: /mm start <map> [player1],[player2],[player3]...'
      already-running: '&cA game is already running'
      shuffle-enabled: '&cShuffle is enabled! Disable it first'
      loop-enabled: '&cLoop is enabled! Disable it first'
      invalid-map: '&c%map% does not exist'
      not-enough-players: '&cThere are not enough players to start a game on %map%'
      invalid-team: '&cThe team name is invalid. (Is it longer than 16 characters?)'
      invalid-objective: '&cThe objective name is invalid. (Is it longer than 16 characters?)'
      success: '&aSuccessfully started Murder Mystery on map %map%'
    shuffle:
      enabled: '&aShuffle is enabled'
      disabled: '&cShuffle has been disabled'
    loop:
      usage: '&cUsage: /mm loop <map> [player1],[player2],[player3]...'
      enabled: '&aLoop is enabled'
      disabled: '&cLoop has been disabled'
    kill:
      usage: '&cUsage: /mm kill <player>'
      success: '&aSuccessfully killed %player%'
      already-dead: '&cThat player is already dead'
    revive:
      usage: '&cUsage: /mm revive <player>'
      success: '&aSuccessfully revived %player%'
      not-dead: '&cThat player is not dead'
    role:
      usage: '&cUsage: /mm role <player>'
      success: '&a%player% is %role%'
    changerole:
      usage: '&cUsage: /mm changerole <player> <role>'
      dead: '&cThat player is dead'
      not-role: '&cThat is not a valid role'
      no-change: '&cThat player already is that role'
      no-bystanders: '&cThere are no bystanders to replace that player with'
      success: '&a%player% is now %role%'
    tt:
      usage: '&cUsage: /mm tt <player>'
      success: '&aThat player is the Murderer'
      failure: '&cThat player is not the Murderer'
    time:
      usage: '&cUsage: /mm time <set|add|remove> <amount>'
      success: '&aSuccessfully changed the time to %time%'
      action: '&cThat is not a valid action, use set/add/remove'
      under-time: '&cThat would give the time a negative value'
    stop:
      usage: '&cUsage: /mm stop'
      success: '&aSuccessfully stopped game on map %map%'
