name: MurderMystery
main: net.trollyloki.murdermystery.MurderMysteryPlugin
version: ${project.version}
api-version: 1.16

author: TrollyLoki
authors: [Arti_Creep]

commands:
  murdermystery:
    permission: murdermystery.admin
    aliases: [mm]